= Raku 介绍
Raku 之美 - <https://rakulang.github.io>; 
:description: 可爱的 Raku
:keywords: raku, lovely, lovely-raku
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: raku
:pygments-linenums-mode: table
:toc: left
:doctype: book
:lang: zh   

Perl 6 的设计进程是从 2000 年开始的。在2000年7月19号 link:http://en.wikipedia.org/wiki/O%27Reilly_Open_Source_Convention[Perl大会]  的第四天, Larry Wall 首次宣布了 Perl 6 的设计进度。

Perl 6 可以有多个实现, 其中第一个完成度最高的实现是开始于 2005 年的 link:https://github.com/raku/Pugs.hs[Pugs], Pugs 解释器是用 link:https://www.haskell.org[Haskell] 实现的, 2015 年以后就没再更新, 但是 Perl 6 设计团队吸收了很多函数式编程的思想。

2015 年12月25日, Perl 6 的第一个稳定的规范发布了。现在完成度最高的 Perl 6 实现是 link:https://rakudo.org[Rakudo], 其使用 link:http://moarvm.org[MoarVM] 或 Java 虚拟机作为运行时环境。

2019 年10月12日, Larry Wall 宣布支持把 Perl 6 link:https://github.com/Raku/problem-solving/pull/89#pullrequestreview-300789072[更名]为 link:https://raku.org[Raku]。

2020 年6月24日, Perl 5 社区宣布将发布 link:https://www.perl.com/article/announcing-perl-7/[Perl 7]。所以, Perl 6 现在就是 Raku 了。 

:sectnums:
== Raku 介绍

=== 安装

link:https://rakudo.org/files[Rakudo Star] 是 Raku 的一个发行版, 由 Rakudo 编译器加上一些包组成, 可以直接下载对应平台的安装包, 按照说明文档进行安装.

如果想体验最新的 Raku 特性, 请自行编译 link:https://github.com/rakudo/rakudo[rakudo]:

[source,shell]
.编译 Raku
----
git clone https://github.com/rakudo/rakudo.git
cd rakudo
perl Configure.pl --gen-moar --gen-nqp --backends=moar --prefix=/opt/rakudo
make
make install
----

安装完 Rakudo Raku 编译器后, 使用自带的 link:https://github.com/ugexe/zef[zef] 安装 `Linenoise` 模块以获得简单的历史命令和自动补全功能.

Linux 用户还可以使用为 Rakudo 预编译好的系统包来安装 Rakudo Raku, 有关详细信息, 请参考 link:https://github.com/nxadm/rakudo-pkg[https://github.com/nxadm/rakudo-pkg].

=== Docker

[source,shell]
.Docker
----
docker pull rakudo-star
----

=== REPL

Raku 自带了一个简陋的 REPL, 用于进行代码的快速测试. 打开系统的终端, 键入 `raku`, 即可进入 REPL, 键入一些 Raku 代码:

[source,shell]
.Read,Evalute,Print,Loop
----
# raku
To exit type 'exit' or '^D'
> [+] 1,2,3
6
> .say for 1..5
1
2
3
4
5
----

目前的 REPL 功能还很简陋, 如果要输入一些复杂的语句, 这个 REPL 就变得不太友好了. 

=== IDE

2019 年3月份, link:https://commaide.com[comma]发布了第一个 Raku 编辑器社区版, 即逗号编辑器, 同时还有 Raku 的 IDEA 插件. 社区版的逗号编辑器功能已经基本够用, 如果你是资深 Raku 开发者或深度 Raku 爱好者, 建议购买完整版.

如果你使用 VSCode/Atom, 那么需要到应用商店安装 Raku 插件.

